### Register User API
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "Shwetabh vikram",
  "email": "vikramshwetabh22@gmail.com",
  "password": "123456",
  "role": "job_seeker"
}
